### ISSUE TITLE
Suggest change to package name and API

### ISSUE THREAD

**Issue by deadprogram** [conejoninja/tinydraw#1]
I'd like to propose 2 changes to this package.

The first is to rename it `tinydraw`.

The second is to change the API to remove the word `Draw` from all of the functions.

For example:

```go
tinydraw.Line(&display, 100, 100, 40, 50, yellow)
tinydraw.Rectangle(&display, 30, 120, 20, 20, black)
tinydraw.FilledRectangle(&display, 34, 124, 12, 12, yellow)
```

**Comment by conejoninja** [comment]
Those are great ideas

I just renamed the repository, we'll made the rest of the changes later, or feel free to send a PR if you can't wait

README & examples need to be modified, primitive.go should be renamed too

**Comment by deadprogram** [comment]
OK, here you go https://github.com/conejoninja/tinydraw/pull/2

**Comment by conejoninja** [comment]
merged
