### ISSUE TITLE
FilledTriangle divide by zero

### ISSUE THREAD

**Issue by spearson78** [conejoninja/tinydraw#10]
While investigating https://github.com/tinygo-org/tinydraw/issues/9 I ran into several divide by zero issues.
I checked the original Adafruit code and found an error in the translation the y variable is reset to last when it should be last+1 from the previous loop.

I created a pull request with the fix. Unfortunately this still doesn't fix https://github.com/tinygo-org/tinydraw/issues/9 but malformed triangles are better than a panic

**Comment by sago35** [comment]
Fixed by #11.
