### ISSUE TITLE
FilledRectangle: w and h are inclusive

### ISSUE THREAD

**Issue by kylelemons** [conejoninja/tinydraw#3]
It is confusing that the following code:

    tinydraw.FilledRectangle(machine.Display, 20, 20, 0, 0, color)

fills in one pixel at 20, 20, and that

    tinydraw.FilledRectangle(machine.Display, 20, 20, 1, 1, color)

fills in 4 pixels.

Typically, I expect the "width" and "height" that I pass into a rectangle function to be number of pixels horizontally and vertically, rather than the offset of the last inclusive point for drawing.

**Comment by conejoninja** [comment]
Thanks, please check if this fix the issue : https://github.com/conejoninja/tinydraw/commit/fdc219c4845bae623b0586e16550fa6c065c0760

**Comment by kylelemons** [comment]
Verified; fixed at top of tree.
